name: Scrape Torob Prices

on:
  schedule:
    # هر روز ساعت 6 صبح به وقت تهران (02:30 UTC)
    - cron: '30 2 * * *'
  workflow_dispatch:  # اجرای دستی
  push:
    branches: [ main ]

jobs:
  scrape-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4
        
    - name: Create products list
      run: |
        mkdir -p data
        echo "تلویزیون سامسونگ 55 اینچ" > data/products.txt
        echo "تلویزیون ال جی 65 اینچ" >> data/products.txt
        echo "تلویزیون سونی 50 اینچ" >> data/products.txt
        echo "تلویزیون شیائومی 43 اینچ" >> data/products.txt
        echo "تلویزیون TCL 50 اینچ" >> data/products.txt
        
    - name: Run scraper
      run: |
        python scripts/scraper.py
        
    - name: Check if data changed
      id: check-changes
      run: |
        git diff --quiet data/torob-data.json || echo "changed=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changed
      if: steps.check-changes.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/torob-data.json
        git commit -m "🔄 Update price data $(date +'%Y-%m-%d %H:%M')"
        git push
